#+TITLE: Design Document 

NOTE: A convention I will be using for this design document if a word is capitalized within the middle of a sentence like Scene, these are classes or interfaces the program will be using.

** Data and Buffers
*** Z-buffer 
Z-buffers will store z information about how far away the closest triangle at the *subpixel* level that means if there are 500 samples per-pixel, then the program must have z-buffer the same size as image_n x image_m x num_samples.
All lighting and cameras will be given z-buffers with respect to their own coordinate systems, cam_u, cam_v, and cam_w, defined as being the camera/light's right (x), up (y), and backward (z) coorientations and the where the light / camera
is placed within the scene. 

*** Vertex Buffer 
A Vertex buffer will store all vertex information in a large std::vector if a user desires to access information the each vector will have a ID; this ID is simply it's index in the std::vector. This buffer avoids duplication of triangle information. In addition to the triangle, this will store the point on the image plane in terms of pixels these amounts may be fractional. 

*** Render Buffer 
Render Buffers will be assigned to the Camera itself. Although lighting objects act as *psuedo* cameras, to tell the program what the light can see and thus how to render the surface, there is no need to output what the light actually sees. Note
that the render buffer will store the final colors of the scene it is what the user will eventually actually see. 

** Meshes 
These objects will store a uint8/16_t mesh-ID, the vec3 color, a pointer to a Material, and a std::vector which will vertex IDs. In the main rendering loop when preforming sub-pixel sampling, the program will pass in the mesh-ID. Much like the vertex-ID the mesh-ID will be an index to an array of Meshes within a Scene.

All meshes at will inherit a function either build() or construct(). These functions will run at compile time and write to a vertex buffer with all the verticies at the desired sample rate. In the case for this project, the test surface will be a UV mesh of a sphere. Once all meshes are drawn, the information is marked read-only. 

At runtime all meshes must have a way for us to find it's normal for Phong shading which means that all Meshes need a find_normal_at() function.

** Scene 
Scenes are only a container for the meshes that the user can interact with this be useful for them when working within main(). The function details are ommited since functions will have obvious names, uses, and implementations.

** Camera 
The Camera is the meat and potatoes of this program and will house all methods relating to rendering using the information figured out at compile time. 

Mentioned before breifly, cameras will have the attributes cam_u, cam_v, and cam_w. The reason for this is to convert the coordinate systems to be in references to the object that we are concerned with. This allows for filling out the z-buffer easy, and since cam_u, cam_v, and cam_w are an orthoginal basis the projection formula simplifies when determining how to color the Render Buffer.

There are two main methods (render and color) with the helper function render_mesh which as the name suggest render meshes onto an Render Buffer. For both render_mesh() and color() the z-buffers for the camera and lighting modules. Also note that projected coordinates need to filled in for the Vertex Buffer since this will allow us to avoid some extra computation. The reason that the z buffer and finding the coordiantes in the Render Buffer are in the same step is because it avoids having to preform recalcuations which would expensive in the below methods.

render_mesh() will use the vertex buffer to create a bounding box and check which points are inside or outside of the triangle by checking the sign of p_k (the point we are checking) crossed with p_i - p_j, where i and j are different points on a triangle. Note that for this algorithim to work, the program has to assign a convention for the "winding" of the triangle, for this project it will be counter-clockwise. With a completed z-buffer the program can determine what triangles are visible or not using the much cheaper euclidean distance instead of a change of basis. The final benefit of this approach is the memory advantage, instead of having to store a large buffer of all the sub-pixels, the program can simply tally how many from each mesh-ID was seen inside of that pixel and pass this new smaller buffer to color().

color() will determine the color of the pixels that we are concerned with additionally because of the completed z-buffer one color is leaves a pixel it must be the correct color. color() will call find_normals_at() for all the verticies of the triangle on the scene. In our specific case since all verticies are lying on the outside of an imaginary sphere, this simply means taking the point on the sphere and subtracting it from the center, and normalizing it which is a cheap operation. The program will use these normals to interpolate normal vectors for the interior of the triangle. 

This color() function will then pass in the mesh_color and all interpolated normals to the Material class's bounce() function.  

After recieving the all the colors for a all triangles in the pixel from bounce(), color() will then finalize the color by averaging the colors using the counts we had earlier and using lighting z-buffers to determine if the triangle that is being colored is in shadow or not. Notice this algorithim actually completely *ignores* the notion of inside and outside because all faces in shadow will be darkened to the point they appear to be in shadow. 

The Phong shading coloring / shading part of the algorithim is applied and the final color is written to the Render buffer. 

TODO: Check the Phong shading formulas and ensure that this final coloring is a feasible design.   

** Materials 
All materials will take in a normal vector to the plane and the location of a light and determine the color as if there are no obstructions between this plane and the light source. This function will be called bounce(), to mimic how it emulates how light bounces of different surfaces. 

For now only glossy objects are going to supported by this project, the Phong shading algorithm has a formula for this that handles the coloring nicely for this application.
